version: "3.9"
services:
  db:
    container_name: dockerbase_db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    container_name: dockerbase_app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/dockerbase
    ports:
      - "3000:3000"
    depends_on:
      - db
